/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__autoencoder_api_cdef
#define __PYX_HAVE__autoencoder_api_cdef

struct NNDimReduce;

/* "autoencoder_api_cdef.pyx":17
 * ########################################################
 * 
 * cdef public class NNDimReduce[object NNDimReduce, type NNDimReduceType]:             # <<<<<<<<<<<<<<
 * 
 *     def __init__(self):
 */
struct NNDimReduce {
  PyObject_HEAD
  struct __pyx_vtabstruct_20autoencoder_api_cdef_NNDimReduce *__pyx_vtab;
};

#ifndef __PYX_HAVE_API__autoencoder_api_cdef

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) NNDimReduceType;

__PYX_EXTERN_C DL_IMPORT(struct NNDimReduce) *buildNNDimReduce(void);
__PYX_EXTERN_C DL_IMPORT(int) accessor_add_data(struct NNDimReduce *, std::vector<double> );
__PYX_EXTERN_C DL_IMPORT(int) accessor_build_dim_reduction(struct NNDimReduce *, int);
__PYX_EXTERN_C DL_IMPORT(std::vector<double> ) accessor_transform_down(struct NNDimReduce *, std::vector<double> , int);

#endif /* !__PYX_HAVE_API__autoencoder_api_cdef */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initautoencoder_api_cdef(void);
#else
PyMODINIT_FUNC PyInit_autoencoder_api_cdef(void);
#endif

#endif /* !__PYX_HAVE__autoencoder_api_cdef */
